/** Cidades das unidades Unimed disponíveis no cabeçalho da receita. */
export const CIDADES_UNIMED: string[] = [
  "Aracaju",
  "Araçatuba",
  "Bauru",
  "Belém",
  "Belo Horizonte",
  "Blumenau",
  "Boa Vista",
  "Brasília",
  "Campina Grande",
  "Campinas",
  "Campo Grande",
  "Caruaru",
  "Cascavel",
  "Caxias do Sul",
  "Chapecó",
  "Cuiabá",
  "Curitiba",
  "Feira de Santana",
  "Florianópolis",
  "Fortaleza",
  "Foz do Iguaçu",
  "Goiânia",
  "Governador Valadares",
  "Ipatinga",
  "Itabuna",
  "Jaraguá do Sul",
  "João Pessoa",
  "Joinville",
  "Juazeiro do Norte",
  "Juiz de Fora",
  "Londrina",
  "Macapá",
  "Maceió",
  "Manaus",
  "Maringá",
  "Marília",
  "Montes Claros",
  "Mossoró",
  "Natal",
  "Niterói",
  "Palmas",
  "Passo Fundo",
  "Pelotas",
  "Petrolina",
  "Piracicaba",
  "Poços de Caldas",
  "Ponta Grossa",
  "Porto Alegre",
  "Porto Velho",
  "Presidente Prudente",
  "Recife",
  "Ribeirão Preto",
  "Rio Branco",
  "Rio de Janeiro",
  "Rio Verde",
  "Salvador",
  "Santa Maria",
  "Santos",
  "São José do Rio Preto",
  "São José dos Campos",
  "São Luís",
  "São Paulo",
  "Sorocaba",
  "Teresina",
  "Uberaba",
  "Uberlândia",
  "Varginha",
  "Vitória",
  "Vitória da Conquista",
  "Volta Redonda",
];
