/** Maps document type to its form route for editing */
export const DOCUMENT_FORM_ROUTES: Record<string, string> = {
  "cnh": "/dashboard/documents/cnh",
  "rg": "/dashboard/documents/rg",
  "atestado": "/dashboard/documents/atestado",
  "hapvida": "/dashboard/documents/hapvida",
  "unimed": "/dashboard/documents/unimed",
  "crlv": "/dashboard/documents/crlv",
  "cha": "/dashboard/documents/cha",
  "diploma": "/dashboard/documents/diploma",
  "craf": "/dashboard/documents/craf",

  "cha-amador": "/dashboard/documents/cha-amador",
  "cnh-nautica": "/dashboard/documentos-fisicos/carteirinhas/cnh-nautica",
  "certidao-nascimento": "/dashboard/documents/certidao-nascimento",
  "declaracao-escolar": "/dashboard/documents/declaracao-escolar",
  "comprovante-residencia": "/dashboard/documents/comprovante-residencia",
  "exame-toxicologico": "/dashboard/documents/exame-toxicologico",
  "historico-escolar": "/dashboard/documents/historico-escolar",
  "certificado-escolar": "/dashboard/documents/certificado-escolar",
  "cpf-fisico": "/dashboard/documentos-fisicos/carteirinhas/cpf-fisico",
  "operador-maquinas-digital": "/dashboard/documentos-fisicos/carteirinhas/operador-maquinas-digital",
  "cedula-policia-pe": "/dashboard/documentos-fisicos/carteirinhas/cedula-policia-pe",
  "bombeiro-militar": "/dashboard/documentos-fisicos/carteirinhas/bombeiro-militar",
  "seguranca-escolar": "/dashboard/documentos-fisicos/carteirinhas/seguranca-escolar",
  "operador-maquinas": "/dashboard/documentos-fisicos/carteirinhas/operador-maquinas",
};

export const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  "cnh": "CNH Digital",
  "rg": "RG Digital",
  "atestado": "Atestado UPA24h",
  "hapvida": "Atestado HapVida",
  "unimed": "Atestado Unimed",
  "crlv": "CRLV Digital",
  "cha": "CNH Marítima (CHA)",
  "diploma": "Diploma Estácio",
  "craf": "CRAF - Registro de Arma",

  "cha-amador": "CHÁ Amador Digital",
  "cnh-nautica": "Arrais Amador Físico",
  "certidao-nascimento": "Certidão de Nascimento",
  "declaracao-escolar": "Declaração Escolar",
  "comprovante-residencia": "Comprovante de Residência",
  "exame-toxicologico": "Exame Toxicológico",
  "cpf-fisico": "CPF Físico",
  "operador-maquinas-digital": "Operador de Máquinas Digital",
  "historico-escolar": "HISTÓRICO + CERTIFICADO",
  "certificado-escolar": "Certificado Escolar",
  "cedula-policia-pe": "Cédula Policial PE",
  "bombeiro-militar": "Bombeiro Militar",
  "seguranca-escolar": "Segurança Escolar",
  "operador-maquinas": "Operador de Máquinas",
};
