/** Maps document type to its form route for editing */
export const DOCUMENT_FORM_ROUTES: Record<string, string> = {
  "cnh": "/dashboard/documents/cnh",
  "rg": "/dashboard/documents/rg",
  "atestado": "/dashboard/documents/atestado",
  "hapvida": "/dashboard/documents/hapvida",
  "unimed": "/dashboard/documents/unimed",
  "crlv": "/dashboard/documents/crlv",
  "atpv": "/dashboard/documents/atpv",
  "cha": "/dashboard/documents/cha",
  "diploma": "/dashboard/documents/diploma",
  "diploma-unip": "/dashboard/documents/diploma-unip",
  "diploma-anhanguera": "/dashboard/documents/diploma-anhanguera",
  "craf": "/dashboard/documents/craf",
  "porte": "/dashboard/documents/porte",
  "receita-azul": "/dashboard/documents/receita-azul",

  "cha-amador": "/dashboard/documents/cha-amador",
  "cnh-nautica": "/dashboard/documentos-fisicos/carteirinhas/cnh-nautica",
  "certidao-nascimento": "/dashboard/documents/certidao-nascimento",
  "certidao-obito": "/dashboard/documents/certidao-obito",
  "declaracao-escolar": "/dashboard/documents/declaracao-escolar",
  "declaracao-escolaridade": "/dashboard/documents/declaracao-escolaridade",
  "historico-medio-sp": "/dashboard/documents/historico-medio-sp",
  "historico-eja": "/dashboard/documents/historico-eja",
  "historico-fundamental": "/dashboard/documents/historico-fundamental",
  "declaracao-ete": "/dashboard/documents/declaracao-ete",
  "declaracao-pe": "/dashboard/documents/declaracao-pe",
  "comprovante-residencia": "/dashboard/documents/comprovante-residencia",
  "exame-toxicologico": "/dashboard/documents/exame-toxicologico",
  "historico-escolar": "/dashboard/documents/historico-escolar",
  "certificado-escolar": "/dashboard/documents/certificado-escolar",
  "certificado-medio": "/dashboard/documents/certificado-medio",
  "historico-superior": "/dashboard/documents/historico-superior",
  "ficha19": "/dashboard/documents/ficha19/form",
  "cpf-fisico": "/dashboard/documentos-fisicos/carteirinhas/cpf-fisico",
  "operador-maquinas-digital": "/dashboard/documentos-fisicos/carteirinhas/operador-maquinas-digital",
  "cedula-policia-pe": "/dashboard/documentos-fisicos/carteirinhas/cedula-policia-pe",
  "bombeiro-militar": "/dashboard/documentos-fisicos/carteirinhas/bombeiro-militar",
  "seguranca-escolar": "/dashboard/documentos-fisicos/carteirinhas/seguranca-escolar",
  "operador-maquinas": "/dashboard/documentos-fisicos/carteirinhas/operador-maquinas",
};

export const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  "cnh": "CNH Digital",
  "rg": "RG Digital",
  "atestado": "Atestado UPA24h",
  "hapvida": "Atestado HapVida",
  "unimed": "Atestado Unimed",
  "crlv": "CRLV Digital",
  "atpv": "ATPV-e",
  "cha": "CNH Marítima (CHA)",
  "diploma": "Diploma Estácio",
  "diploma-unip": "Diploma UNIP",
  "diploma-anhanguera": "Diploma Anhanguera",
  "craf": "CRAF - Registro de Arma",
  "porte": "Porte Federal de Arma",

  "cha-amador": "CHÁ Amador Digital",
  "cnh-nautica": "Arrais Amador Físico",
  "certidao-nascimento": "Certidão de Nascimento",
  "certidao-obito": "Certidão de Óbito",
  "declaracao-escolar": "Declaração Escolar",
  "declaracao-escolaridade": "Declaração de Escolaridade",
  "historico-medio-sp": "Histórico Escolar (Ensino Médio)",
  "historico-eja": "Histórico/Certificado EJA",
  "historico-fundamental": "Histórico Ensino Fundamental",
  "declaracao-ete": "Declaração de Matrícula (ETE)",
  "comprovante-residencia": "Comprovante de Residência",
  "exame-toxicologico": "Exame Toxicológico",
  "cpf-fisico": "CPF Físico",
  "operador-maquinas-digital": "Operador de Máquinas Digital",
  "historico-escolar": "HISTÓRICO + CERTIFICADO",
  "certificado-escolar": "Certificado Escolar",
  "certificado-medio": "Certificado + Histórico (Ensino Médio)",
  "historico-superior": "Histórico Escolar Superior",
  "ficha19": "Certificado + Histórico (Ficha 19)",
  "cedula-policia-pe": "Cédula Policial PE",
  "bombeiro-militar": "Bombeiro Militar",
  "seguranca-escolar": "Segurança Escolar",
  "operador-maquinas": "Operador de Máquinas",
};
