// Base de medicamentos — gerado/curado para o buscador da Receita Médica
export interface MedBase { n: string; f: string[]; d: string[]; p: number }

export const FORMAS: Record<string, string> = {
  "cp": "Comprimido",
  "cpr": "Comprimido revestido",
  "cap": "Cápsula",
  "capm": "Cápsula mole",
  "xar": "Xarope",
  "sus": "Suspensão oral",
  "sol": "Solução oral",
  "got": "Solução oral (gotas)",
  "inj": "Solução injetável",
  "pom": "Pomada",
  "cre": "Creme",
  "gel": "Gel",
  "spr": "Spray/Aerossol",
  "col": "Colírio",
  "cot": "Solução otológica",
  "sup": "Supositório",
  "ade": "Adesivo transdérmico",
  "sac": "Sachê / Pó",
  "efe": "Comprimido efervescente",
  "sub": "Comprimido sublingual",
  "past": "Pastilha",
  "sham": "Shampoo",
  "oral": "Colutório",
  "loc": "Loção",
  "ovu": "Óvulo vaginal"
};

export const MEDICAMENTOS: MedBase[] = [
  {"n": "Dipirona sódica","f": ["cp","got","sol","inj","sup"],"d": ["500 mg","1 g","500 mg/mL","300 mg"],"p": 1},
  {"n": "Paracetamol","f": ["cp","got","sol","sus"],"d": ["500 mg","750 mg","200 mg/mL","100 mg/mL"],"p": 1},
  {"n": "Ibuprofeno","f": ["cp","capm","sus","got"],"d": ["200 mg","300 mg","400 mg","600 mg","50 mg/mL","100 mg/mL"],"p": 1},
  {"n": "Nimesulida","f": ["cp","got","sac"],"d": ["100 mg","50 mg/mL"],"p": 0},
  {"n": "Diclofenaco sódico","f": ["cpr","inj","gel","sup"],"d": ["50 mg","75 mg/3 mL","10 mg/g"],"p": 0},
  {"n": "Diclofenaco potássico","f": ["cpr","sus","got"],"d": ["50 mg","15 mg/mL"],"p": 0},
  {"n": "Cetoprofeno","f": ["cp","capm","inj","gel"],"d": ["50 mg","100 mg","150 mg","2","5%"],"p": 0},
  {"n": "Naproxeno","f": ["cp"],"d": ["250 mg","500 mg"],"p": 0},
  {"n": "Piroxicam","f": ["cp","cap","inj"],"d": ["10 mg","20 mg"],"p": 0},
  {"n": "Meloxicam","f": ["cp","inj"],"d": ["7","5 mg","15 mg"],"p": 0},
  {"n": "Celecoxibe","f": ["cap"],"d": ["100 mg","200 mg"],"p": 0},
  {"n": "Etoricoxibe","f": ["cpr"],"d": ["60 mg","90 mg","120 mg"],"p": 0},
  {"n": "Ácido acetilsalicílico","f": ["cp"],"d": ["100 mg","325 mg","500 mg"],"p": 1},
  {"n": "Cetorolaco de trometamol","f": ["sub","inj"],"d": ["10 mg","30 mg/mL"],"p": 0},
  {"n": "Tenoxicam","f": ["cp","inj"],"d": ["20 mg"],"p": 0},
  {"n": "Indometacina","f": ["cap"],"d": ["25 mg","50 mg"],"p": 0},
  {"n": "Ácido mefenâmico","f": ["cp"],"d": ["500 mg"],"p": 0},
  {"n": "Paracetamol + Cafeína","f": ["cp"],"d": ["500 mg + 65 mg"],"p": 0},
  {"n": "Paracetamol + Codeína","f": ["cp"],"d": ["500 mg + 30 mg","500 mg + 7","5 mg"],"p": 0},
  {"n": "Dipirona + Escopolamina","f": ["cp","got","inj"],"d": ["500 mg + 10 mg","500 mg/mL + 6","67 mg/mL"],"p": 0},
  {"n": "Escopolamina (Buscopan)","f": ["cp","got","inj"],"d": ["10 mg","20 mg/mL"],"p": 0},
  {"n": "Tramadol","f": ["cap","cp","got","inj"],"d": ["50 mg","100 mg","100 mg/mL"],"p": 0},
  {"n": "Tramadol + Paracetamol","f": ["cpr"],"d": ["37","5 mg + 325 mg"],"p": 0},
  {"n": "Codeína","f": ["cp","sol"],"d": ["30 mg","60 mg","3 mg/mL"],"p": 0},
  {"n": "Morfina","f": ["cp","sol","inj"],"d": ["10 mg","30 mg","10 mg/mL"],"p": 0},
  {"n": "Nalbufina","f": ["inj"],"d": ["10 mg/mL"],"p": 0},
  {"n": "Amoxicilina","f": ["cap","sus","cp"],"d": ["250 mg","500 mg","875 mg","250 mg/5 mL","400 mg/5 mL"],"p": 1},
  {"n": "Amoxicilina + Clavulanato","f": ["cpr","sus"],"d": ["500 mg + 125 mg","875 mg + 125 mg","250 mg + 62","5 mg/5 mL"],"p": 0},
  {"n": "Ampicilina","f": ["cap","sus","inj"],"d": ["500 mg","250 mg/5 mL","1 g"],"p": 0},
  {"n": "Azitromicina","f": ["cpr","sus"],"d": ["500 mg","600 mg","200 mg/5 mL"],"p": 0},
  {"n": "Claritromicina","f": ["cpr","sus"],"d": ["250 mg","500 mg","250 mg/5 mL"],"p": 0},
  {"n": "Eritromicina","f": ["cpr","sus"],"d": ["500 mg","250 mg/5 mL"],"p": 0},
  {"n": "Cefalexina","f": ["cap","sus","cp"],"d": ["500 mg","250 mg/5 mL","500 mg/5 mL"],"p": 1},
  {"n": "Cefadroxila","f": ["cap","sus"],"d": ["500 mg","250 mg/5 mL"],"p": 0},
  {"n": "Cefaclor","f": ["cap","sus"],"d": ["500 mg","250 mg/5 mL"],"p": 0},
  {"n": "Cefuroxima","f": ["cpr","sus"],"d": ["250 mg","500 mg"],"p": 0},
  {"n": "Ceftriaxona","f": ["inj"],"d": ["250 mg","500 mg","1 g"],"p": 0},
  {"n": "Ciprofloxacino","f": ["cpr","inj","col"],"d": ["250 mg","500 mg","2 mg/mL","3","5 mg/mL"],"p": 1},
  {"n": "Levofloxacino","f": ["cpr","inj"],"d": ["250 mg","500 mg","750 mg"],"p": 0},
  {"n": "Moxifloxacino","f": ["cpr"],"d": ["400 mg"],"p": 0},
  {"n": "Norfloxacino","f": ["cpr"],"d": ["400 mg"],"p": 0},
  {"n": "Sulfametoxazol + Trimetoprima","f": ["cp","sus"],"d": ["400 mg + 80 mg","800 mg + 160 mg","200 mg + 40 mg/5 mL"],"p": 1},
  {"n": "Metronidazol","f": ["cp","sus","gel","inj"],"d": ["250 mg","400 mg","40 mg/mL","100 mg/g"],"p": 0},
  {"n": "Secnidazol","f": ["cp"],"d": ["500 mg","1 g"],"p": 0},
  {"n": "Tinidazol","f": ["cp"],"d": ["500 mg"],"p": 0},
  {"n": "Nitrofurantoína","f": ["cap"],"d": ["100 mg"],"p": 0},
  {"n": "Fosfomicina trometamol","f": ["sac"],"d": ["3 g"],"p": 0},
  {"n": "Clindamicina","f": ["cap","inj","cre"],"d": ["300 mg","150 mg/mL","20 mg/g"],"p": 0},
  {"n": "Doxiciclina","f": ["cp","cap"],"d": ["100 mg"],"p": 0},
  {"n": "Tetraciclina","f": ["cap"],"d": ["500 mg"],"p": 0},
  {"n": "Minociclina","f": ["cap"],"d": ["100 mg"],"p": 0},
  {"n": "Gentamicina","f": ["inj","col","pom"],"d": ["40 mg/mL","5 mg/mL","1 mg/g"],"p": 0},
  {"n": "Vancomicina","f": ["inj"],"d": ["500 mg","1 g"],"p": 0},
  {"n": "Penicilina G Benzatina","f": ["inj"],"d": ["600.000 UI","1.200.000 UI"],"p": 0},
  {"n": "Rifampicina","f": ["cap","sus"],"d": ["300 mg","20 mg/mL"],"p": 0},
  {"n": "Isoniazida","f": ["cp"],"d": ["100 mg","300 mg"],"p": 0},
  {"n": "Fluconazol","f": ["cap","inj"],"d": ["150 mg","100 mg","2 mg/mL"],"p": 0},
  {"n": "Itraconazol","f": ["cap"],"d": ["100 mg"],"p": 0},
  {"n": "Cetoconazol","f": ["cp","cre","sham"],"d": ["200 mg","20 mg/g"],"p": 0},
  {"n": "Terbinafina","f": ["cp","cre"],"d": ["250 mg","10 mg/g"],"p": 0},
  {"n": "Nistatina","f": ["sus","cre"],"d": ["100.000 UI/mL","25.000 UI/g"],"p": 0},
  {"n": "Miconazol","f": ["cre","gel"],"d": ["20 mg/g"],"p": 0},
  {"n": "Clotrimazol","f": ["cre"],"d": ["10 mg/g"],"p": 0},
  {"n": "Aciclovir","f": ["cp","cre","inj"],"d": ["200 mg","400 mg","50 mg/g"],"p": 1},
  {"n": "Valaciclovir","f": ["cpr"],"d": ["500 mg","1 g"],"p": 0},
  {"n": "Oseltamivir","f": ["cap"],"d": ["30 mg","45 mg","75 mg"],"p": 0},
  {"n": "Albendazol","f": ["cp","sus"],"d": ["400 mg","40 mg/mL"],"p": 0},
  {"n": "Mebendazol","f": ["cp","sus"],"d": ["100 mg","500 mg","20 mg/mL"],"p": 0},
  {"n": "Ivermectina","f": ["cp"],"d": ["6 mg"],"p": 0},
  {"n": "Praziquantel","f": ["cp"],"d": ["600 mg"],"p": 0},
  {"n": "Nitazoxanida","f": ["cp","sus"],"d": ["500 mg","20 mg/mL"],"p": 0},
  {"n": "Loratadina","f": ["cp","xar"],"d": ["10 mg","1 mg/mL"],"p": 1},
  {"n": "Desloratadina","f": ["cp","xar"],"d": ["5 mg","0","5 mg/mL"],"p": 0},
  {"n": "Cetirizina","f": ["cp","got"],"d": ["10 mg","10 mg/mL"],"p": 0},
  {"n": "Levocetirizina","f": ["cp","got"],"d": ["5 mg","5 mg/mL"],"p": 0},
  {"n": "Fexofenadina","f": ["cpr","sus"],"d": ["60 mg","120 mg","180 mg","6 mg/mL"],"p": 0},
  {"n": "Dexclorfeniramina","f": ["cp","xar"],"d": ["2 mg","0","4 mg/mL"],"p": 0},
  {"n": "Hidroxizina","f": ["cp","xar"],"d": ["25 mg","2 mg/mL"],"p": 0},
  {"n": "Prometazina","f": ["cp","inj"],"d": ["25 mg","50 mg/2 mL"],"p": 0},
  {"n": "Ebastina","f": ["cp"],"d": ["10 mg"],"p": 0},
  {"n": "Bilastina","f": ["cp"],"d": ["20 mg"],"p": 0},
  {"n": "Rupatadina","f": ["cp"],"d": ["10 mg"],"p": 0},
  {"n": "Prednisona","f": ["cp"],"d": ["5 mg","20 mg"],"p": 1},
  {"n": "Prednisolona","f": ["cp","sol"],"d": ["3 mg/mL","20 mg","40 mg"],"p": 1},
  {"n": "Dexametasona","f": ["cp","inj","cre","col"],"d": ["4 mg","0","75 mg","4 mg/mL","1 mg/g"],"p": 0},
  {"n": "Betametasona","f": ["inj","cre","sol"],"d": ["4 mg/mL","1 mg/g"],"p": 0},
  {"n": "Hidrocortisona","f": ["inj","cre"],"d": ["100 mg","500 mg","10 mg/g"],"p": 0},
  {"n": "Metilprednisolona","f": ["cp","inj"],"d": ["4 mg","16 mg","500 mg"],"p": 0},
  {"n": "Deflazacorte","f": ["cp"],"d": ["6 mg","30 mg"],"p": 0},
  {"n": "Budesonida","f": ["spr","sus"],"d": ["32 mcg/dose","50 mcg/dose","64 mcg/dose","0","25 mg/mL","0","5 mg/mL"],"p": 1},
  {"n": "Budesonida + Formoterol","f": ["spr"],"d": ["6/200 mcg","6/100 mcg","12/400 mcg"],"p": 0},
  {"n": "Mometasona","f": ["spr","cre"],"d": ["50 mcg/dose","1 mg/g"],"p": 0},
  {"n": "Fluticasona","f": ["spr"],"d": ["50 mcg/dose"],"p": 0},
  {"n": "Beclometasona","f": ["spr"],"d": ["50 mcg/dose","250 mcg/dose"],"p": 0},
  {"n": "Salbutamol","f": ["spr","sol","cp"],"d": ["100 mcg/dose","5 mg/mL","2 mg"],"p": 1},
  {"n": "Fenoterol","f": ["got"],"d": ["5 mg/mL"],"p": 0},
  {"n": "Ipratrópio","f": ["got","spr"],"d": ["0","25 mg/mL","20 mcg/dose"],"p": 0},
  {"n": "Formoterol","f": ["spr"],"d": ["12 mcg"],"p": 0},
  {"n": "Salmeterol + Fluticasona","f": ["spr"],"d": ["25/125 mcg","25/250 mcg","50/250 mcg"],"p": 0},
  {"n": "Montelucaste","f": ["cp","sac"],"d": ["4 mg","5 mg","10 mg"],"p": 0},
  {"n": "Aminofilina","f": ["cp","inj"],"d": ["100 mg","200 mg","24 mg/mL"],"p": 0},
  {"n": "Acetilcisteína","f": ["sac","xar","efe"],"d": ["100 mg","200 mg","600 mg","20 mg/mL","40 mg/mL"],"p": 0},
  {"n": "Ambroxol","f": ["xar","sol"],"d": ["3 mg/mL","6 mg/mL","15 mg/5 mL"],"p": 0},
  {"n": "Bromexina","f": ["xar"],"d": ["4 mg/5 mL","8 mg/5 mL"],"p": 0},
  {"n": "Carbocisteína","f": ["xar"],"d": ["20 mg/mL","50 mg/mL"],"p": 0},
  {"n": "Guaifenesina","f": ["xar"],"d": ["100 mg/5 mL"],"p": 0},
  {"n": "Dropropizina","f": ["xar"],"d": ["1","5 mg/mL","3 mg/mL"],"p": 0},
  {"n": "Levodropropizina","f": ["xar"],"d": ["6 mg/mL"],"p": 0},
  {"n": "Dextrometorfano","f": ["xar"],"d": ["15 mg/5 mL"],"p": 0},
  {"n": "Clobutinol + Doxilamina","f": ["got","xar"],"d": ["20 mg/mL","4 mg/mL"],"p": 0},
  {"n": "Hexomedine","f": ["oral"],"d": ["1 mg/mL + 0","5 mg/mL"],"p": 0},
  {"n": "Benzocaína + Cetilpiridínio","f": ["past","spr"],"d": ["Pastilha","Spray"],"p": 0},
  {"n": "Cloridrato de Benzidamina","f": ["oral","spr"],"d": ["1","5 mg/mL","0","15%"],"p": 0},
  {"n": "Omeprazol","f": ["cap"],"d": ["10 mg","20 mg","40 mg"],"p": 1},
  {"n": "Pantoprazol","f": ["cpr","inj"],"d": ["20 mg","40 mg"],"p": 0},
  {"n": "Esomeprazol","f": ["cap","cpr"],"d": ["20 mg","40 mg"],"p": 0},
  {"n": "Lansoprazol","f": ["cap"],"d": ["15 mg","30 mg"],"p": 0},
  {"n": "Rabeprazol","f": ["cpr"],"d": ["10 mg","20 mg"],"p": 0},
  {"n": "Ranitidina","f": ["cp","inj"],"d": ["150 mg","300 mg","25 mg/mL"],"p": 0},
  {"n": "Famotidina","f": ["cp"],"d": ["20 mg","40 mg"],"p": 0},
  {"n": "Domperidona","f": ["cp","sus"],"d": ["10 mg","1 mg/mL"],"p": 0},
  {"n": "Metoclopramida","f": ["cp","got","inj"],"d": ["10 mg","4 mg/mL","5 mg/mL"],"p": 0},
  {"n": "Bromoprida","f": ["cap","got","inj"],"d": ["10 mg","4 mg/mL","5 mg/mL"],"p": 0},
  {"n": "Ondansetrona","f": ["cp","sub","inj"],"d": ["4 mg","8 mg","2 mg/mL"],"p": 0},
  {"n": "Dimenidrinato + Piridoxina","f": ["cp","got","inj"],"d": ["50 mg + 10 mg","25 mg/mL"],"p": 0},
  {"n": "Simeticona","f": ["got","cp"],"d": ["75 mg/mL","40 mg","125 mg"],"p": 0},
  {"n": "Hidróxido de alumínio","f": ["sus"],"d": ["61","5 mg/mL"],"p": 0},
  {"n": "Sais de reidratação oral","f": ["sac"],"d": ["Envelope"],"p": 0},
  {"n": "Loperamida","f": ["cp"],"d": ["2 mg"],"p": 0},
  {"n": "Racecadotrila","f": ["cap","sac"],"d": ["100 mg","10 mg","30 mg"],"p": 0},
  {"n": "Saccharomyces boulardii","f": ["cap","sac"],"d": ["100 mg","200 mg"],"p": 0},
  {"n": "Lactulose","f": ["xar"],"d": ["667 mg/mL"],"p": 0},
  {"n": "Bisacodil","f": ["cpr"],"d": ["5 mg"],"p": 0},
  {"n": "Óleo mineral","f": ["sol"],"d": ["100%"],"p": 0},
  {"n": "Picossulfato de sódio","f": ["got"],"d": ["7","5 mg/mL"],"p": 0},
  {"n": "Polietilenoglicol","f": ["sac"],"d": ["14 g","17 g"],"p": 0},
  {"n": "Enalapril","f": ["cp"],"d": ["5 mg","10 mg","20 mg"],"p": 1},
  {"n": "Captopril","f": ["cp"],"d": ["12","5 mg","25 mg","50 mg"],"p": 1},
  {"n": "Lisinopril","f": ["cp"],"d": ["5 mg","10 mg","20 mg"],"p": 0},
  {"n": "Ramipril","f": ["cp"],"d": ["2","5 mg","5 mg","10 mg"],"p": 0},
  {"n": "Losartana potássica","f": ["cpr"],"d": ["25 mg","50 mg","100 mg"],"p": 1},
  {"n": "Valsartana","f": ["cpr"],"d": ["80 mg","160 mg","320 mg"],"p": 0},
  {"n": "Olmesartana","f": ["cpr"],"d": ["20 mg","40 mg"],"p": 0},
  {"n": "Candesartana","f": ["cp"],"d": ["8 mg","16 mg"],"p": 0},
  {"n": "Telmisartana","f": ["cp"],"d": ["40 mg","80 mg"],"p": 0},
  {"n": "Irbesartana","f": ["cp"],"d": ["150 mg","300 mg"],"p": 0},
  {"n": "Anlodipino","f": ["cp"],"d": ["2","5 mg","5 mg","10 mg"],"p": 1},
  {"n": "Nifedipino","f": ["cpr"],"d": ["10 mg","20 mg","30 mg","60 mg"],"p": 0},
  {"n": "Verapamil","f": ["cpr"],"d": ["80 mg","120 mg","240 mg"],"p": 0},
  {"n": "Diltiazem","f": ["cpr","cap"],"d": ["30 mg","60 mg","90 mg","120 mg"],"p": 0},
  {"n": "Atenolol","f": ["cp"],"d": ["25 mg","50 mg","100 mg"],"p": 1},
  {"n": "Propranolol","f": ["cp"],"d": ["10 mg","40 mg","80 mg"],"p": 1},
  {"n": "Metoprolol","f": ["cpr"],"d": ["25 mg","50 mg","100 mg"],"p": 0},
  {"n": "Carvedilol","f": ["cp"],"d": ["3","125 mg","6","25 mg","12","5 mg","25 mg"],"p": 1},
  {"n": "Bisoprolol","f": ["cpr"],"d": ["1","25 mg","2","5 mg","5 mg","10 mg"],"p": 0},
  {"n": "Nebivolol","f": ["cp"],"d": ["5 mg"],"p": 0},
  {"n": "Hidroclorotiazida","f": ["cp"],"d": ["12","5 mg","25 mg","50 mg"],"p": 1},
  {"n": "Clortalidona","f": ["cp"],"d": ["12","5 mg","25 mg","50 mg"],"p": 0},
  {"n": "Indapamida","f": ["cpr"],"d": ["1","5 mg","2","5 mg"],"p": 0},
  {"n": "Furosemida","f": ["cp","inj"],"d": ["40 mg","10 mg/mL"],"p": 1},
  {"n": "Espironolactona","f": ["cp"],"d": ["25 mg","50 mg","100 mg"],"p": 1},
  {"n": "Metildopa","f": ["cpr"],"d": ["250 mg","500 mg"],"p": 1},
  {"n": "Clonidina","f": ["cp"],"d": ["0","100 mg","0","150 mg","0","200 mg"],"p": 0},
  {"n": "Hidralazina","f": ["cp","inj"],"d": ["25 mg","50 mg","20 mg/mL"],"p": 0},
  {"n": "Isossorbida (mononitrato)","f": ["cpr"],"d": ["20 mg","40 mg"],"p": 0},
  {"n": "Isossorbida (dinitrato)","f": ["sub"],"d": ["5 mg"],"p": 0},
  {"n": "Propatilnitrato","f": ["cp"],"d": ["10 mg"],"p": 0},
  {"n": "Sinvastatina","f": ["cpr"],"d": ["10 mg","20 mg","40 mg"],"p": 1},
  {"n": "Atorvastatina","f": ["cpr"],"d": ["10 mg","20 mg","40 mg","80 mg"],"p": 0},
  {"n": "Rosuvastatina","f": ["cpr"],"d": ["5 mg","10 mg","20 mg","40 mg"],"p": 0},
  {"n": "Pravastatina","f": ["cp"],"d": ["20 mg","40 mg"],"p": 0},
  {"n": "Ezetimiba","f": ["cp"],"d": ["10 mg"],"p": 0},
  {"n": "Ezetimiba + Sinvastatina","f": ["cp"],"d": ["10/20 mg","10/40 mg"],"p": 0},
  {"n": "Fenofibrato","f": ["cap"],"d": ["160 mg","200 mg","250 mg"],"p": 0},
  {"n": "Ciprofibrato","f": ["cp"],"d": ["100 mg"],"p": 0},
  {"n": "Bezafibrato","f": ["cpr"],"d": ["200 mg","400 mg"],"p": 0},
  {"n": "Ácidos graxos ômega 3","f": ["capm"],"d": ["1000 mg"],"p": 0},
  {"n": "Clopidogrel","f": ["cpr"],"d": ["75 mg"],"p": 0},
  {"n": "Varfarina","f": ["cp"],"d": ["1 mg","2","5 mg","5 mg"],"p": 0},
  {"n": "Rivaroxabana","f": ["cpr"],"d": ["10 mg","15 mg","20 mg"],"p": 0},
  {"n": "Apixabana","f": ["cpr"],"d": ["2","5 mg","5 mg"],"p": 0},
  {"n": "Enoxaparina","f": ["inj"],"d": ["20 mg","40 mg","60 mg","80 mg"],"p": 0},
  {"n": "Cilostazol","f": ["cp"],"d": ["50 mg","100 mg"],"p": 0},
  {"n": "Pentoxifilina","f": ["cpr"],"d": ["400 mg"],"p": 0},
  {"n": "Metformina","f": ["cpr"],"d": ["500 mg","850 mg","1 g"],"p": 1},
  {"n": "Glibenclamida","f": ["cp"],"d": ["5 mg"],"p": 1},
  {"n": "Gliclazida","f": ["cpr"],"d": ["30 mg","60 mg","80 mg"],"p": 1},
  {"n": "Glimepirida","f": ["cp"],"d": ["1 mg","2 mg","4 mg"],"p": 0},
  {"n": "Dapagliflozina","f": ["cpr"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Empagliflozina","f": ["cpr"],"d": ["10 mg","25 mg"],"p": 0},
  {"n": "Sitagliptina","f": ["cpr"],"d": ["25 mg","50 mg","100 mg"],"p": 0},
  {"n": "Vildagliptina","f": ["cp"],"d": ["50 mg"],"p": 0},
  {"n": "Linagliptina","f": ["cpr"],"d": ["5 mg"],"p": 0},
  {"n": "Pioglitazona","f": ["cp"],"d": ["15 mg","30 mg","45 mg"],"p": 0},
  {"n": "Insulina NPH","f": ["inj"],"d": ["100 UI/mL"],"p": 1},
  {"n": "Insulina Regular","f": ["inj"],"d": ["100 UI/mL"],"p": 1},
  {"n": "Insulina Glargina","f": ["inj"],"d": ["100 UI/mL"],"p": 0},
  {"n": "Insulina Lispro","f": ["inj"],"d": ["100 UI/mL"],"p": 0},
  {"n": "Liraglutida","f": ["inj"],"d": ["6 mg/mL"],"p": 0},
  {"n": "Semaglutida","f": ["inj","cp"],"d": ["0","25 mg","0","5 mg","1 mg","7 mg","14 mg"],"p": 0},
  {"n": "Levotiroxina sódica","f": ["cp"],"d": ["25 mcg","50 mcg","75 mcg","88 mcg","100 mcg","112 mcg","125 mcg","150 mcg"],"p": 1},
  {"n": "Metimazol","f": ["cp"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Propiltiouracila","f": ["cp"],"d": ["100 mg"],"p": 0},
  {"n": "Alendronato de sódio","f": ["cp"],"d": ["10 mg","70 mg"],"p": 1},
  {"n": "Risedronato","f": ["cpr"],"d": ["35 mg","150 mg"],"p": 0},
  {"n": "Carbonato de cálcio + Vitamina D","f": ["cp"],"d": ["500 mg + 400 UI","600 mg + 400 UI"],"p": 0},
  {"n": "Colecalciferol (Vitamina D3)","f": ["cap","got"],"d": ["1.000 UI","2.000 UI","7.000 UI","50.000 UI","200 UI/gota"],"p": 0},
  {"n": "Sulfato ferroso","f": ["cp","got"],"d": ["40 mg","25 mg/mL"],"p": 1},
  {"n": "Ácido fólico","f": ["cp"],"d": ["5 mg","0","4 mg"],"p": 1},
  {"n": "Cianocobalamina (B12)","f": ["cp","inj"],"d": ["1 mg","5.000 mcg"],"p": 0},
  {"n": "Complexo B","f": ["cp","inj","sol"],"d": ["Comprimido","Ampola"],"p": 0},
  {"n": "Vitamina C (Ácido ascórbico)","f": ["cp","efe","got"],"d": ["500 mg","1 g","200 mg/mL"],"p": 0},
  {"n": "Polivitamínico","f": ["cap","cp"],"d": ["Cápsula","Comprimido"],"p": 0},
  {"n": "Cloreto de potássio","f": ["cp","xar"],"d": ["600 mg","6%"],"p": 0},
  {"n": "Sulfato de magnésio","f": ["inj"],"d": ["500 mg/mL"],"p": 0},
  {"n": "Cloridrato de tiamina (B1)","f": ["cp","inj"],"d": ["300 mg","100 mg/mL"],"p": 0},
  {"n": "Fluoxetina","f": ["cap","cp","sol"],"d": ["10 mg","20 mg","20 mg/mL"],"p": 1},
  {"n": "Sertralina","f": ["cpr"],"d": ["25 mg","50 mg","100 mg"],"p": 0},
  {"n": "Escitalopram","f": ["cpr","got"],"d": ["10 mg","15 mg","20 mg","20 mg/mL"],"p": 0},
  {"n": "Citalopram","f": ["cpr"],"d": ["20 mg","40 mg"],"p": 0},
  {"n": "Paroxetina","f": ["cpr"],"d": ["10 mg","20 mg","30 mg"],"p": 0},
  {"n": "Venlafaxina","f": ["cap"],"d": ["37","5 mg","75 mg","150 mg"],"p": 0},
  {"n": "Desvenlafaxina","f": ["cpr"],"d": ["50 mg","100 mg"],"p": 0},
  {"n": "Duloxetina","f": ["cap"],"d": ["30 mg","60 mg"],"p": 0},
  {"n": "Bupropiona","f": ["cpr"],"d": ["150 mg","300 mg"],"p": 0},
  {"n": "Mirtazapina","f": ["cpr"],"d": ["15 mg","30 mg","45 mg"],"p": 0},
  {"n": "Trazodona","f": ["cpr"],"d": ["50 mg","100 mg","150 mg"],"p": 0},
  {"n": "Amitriptilina","f": ["cpr"],"d": ["25 mg","75 mg"],"p": 1},
  {"n": "Nortriptilina","f": ["cap"],"d": ["10 mg","25 mg","50 mg"],"p": 0},
  {"n": "Imipramina","f": ["cp"],"d": ["25 mg"],"p": 0},
  {"n": "Clomipramina","f": ["cpr"],"d": ["10 mg","25 mg","75 mg"],"p": 0},
  {"n": "Vortioxetina","f": ["cpr"],"d": ["10 mg","20 mg"],"p": 0},
  {"n": "Clonazepam","f": ["cp","got"],"d": ["0","5 mg","2 mg","2","5 mg/mL"],"p": 0},
  {"n": "Alprazolam","f": ["cp"],"d": ["0","25 mg","0","5 mg","1 mg","2 mg"],"p": 0},
  {"n": "Diazepam","f": ["cp","inj"],"d": ["5 mg","10 mg","5 mg/mL"],"p": 0},
  {"n": "Lorazepam","f": ["cp"],"d": ["1 mg","2 mg"],"p": 0},
  {"n": "Bromazepam","f": ["cp"],"d": ["3 mg","6 mg"],"p": 0},
  {"n": "Midazolam","f": ["cp","inj"],"d": ["7","5 mg","15 mg","5 mg/mL"],"p": 0},
  {"n": "Zolpidem","f": ["cpr","sub"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Buspirona","f": ["cp"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Quetiapina","f": ["cpr"],"d": ["25 mg","100 mg","200 mg","300 mg"],"p": 0},
  {"n": "Risperidona","f": ["cp","sol"],"d": ["1 mg","2 mg","3 mg","1 mg/mL"],"p": 0},
  {"n": "Olanzapina","f": ["cpr"],"d": ["2","5 mg","5 mg","10 mg"],"p": 0},
  {"n": "Aripiprazol","f": ["cp"],"d": ["10 mg","15 mg","20 mg","30 mg"],"p": 0},
  {"n": "Haloperidol","f": ["cp","got","inj"],"d": ["1 mg","5 mg","2 mg/mL","5 mg/mL"],"p": 0},
  {"n": "Clorpromazina","f": ["cp","got"],"d": ["25 mg","100 mg","40 mg/mL"],"p": 0},
  {"n": "Lítio (Carbonato)","f": ["cp"],"d": ["300 mg","450 mg"],"p": 0},
  {"n": "Lamotrigina","f": ["cp"],"d": ["25 mg","50 mg","100 mg"],"p": 0},
  {"n": "Ácido valproico / Valproato","f": ["cap","xar","cpr"],"d": ["250 mg","500 mg","50 mg/mL"],"p": 0},
  {"n": "Carbamazepina","f": ["cp","sus"],"d": ["200 mg","400 mg","20 mg/mL"],"p": 0},
  {"n": "Oxcarbazepina","f": ["cpr","sus"],"d": ["300 mg","600 mg","60 mg/mL"],"p": 0},
  {"n": "Fenitoína","f": ["cp","inj"],"d": ["100 mg","50 mg/mL"],"p": 0},
  {"n": "Fenobarbital","f": ["cp","got"],"d": ["50 mg","100 mg","40 mg/mL"],"p": 0},
  {"n": "Topiramato","f": ["cpr"],"d": ["25 mg","50 mg","100 mg"],"p": 0},
  {"n": "Levetiracetam","f": ["cpr","sol"],"d": ["250 mg","500 mg","1 g","100 mg/mL"],"p": 0},
  {"n": "Gabapentina","f": ["cap"],"d": ["300 mg","400 mg","600 mg"],"p": 0},
  {"n": "Pregabalina","f": ["cap"],"d": ["25 mg","50 mg","75 mg","150 mg","300 mg"],"p": 0},
  {"n": "Metilfenidato","f": ["cp","cap"],"d": ["10 mg","18 mg","30 mg","36 mg","54 mg"],"p": 0},
  {"n": "Lisdexanfetamina","f": ["cap"],"d": ["30 mg","50 mg","70 mg"],"p": 0},
  {"n": "Donepezila","f": ["cpr"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Memantina","f": ["cpr"],"d": ["10 mg","20 mg"],"p": 0},
  {"n": "Levodopa + Carbidopa","f": ["cp"],"d": ["250/25 mg","200/50 mg"],"p": 0},
  {"n": "Levodopa + Benserazida","f": ["cp"],"d": ["200/50 mg","100/25 mg"],"p": 0},
  {"n": "Pramipexol","f": ["cp"],"d": ["0","125 mg","0","25 mg","1 mg"],"p": 0},
  {"n": "Biperideno","f": ["cp"],"d": ["2 mg"],"p": 0},
  {"n": "Sumatriptano","f": ["cp"],"d": ["50 mg","100 mg"],"p": 0},
  {"n": "Naratriptano","f": ["cp"],"d": ["2","5 mg"],"p": 0},
  {"n": "Rizatriptano","f": ["sub"],"d": ["10 mg"],"p": 0},
  {"n": "Flunarizina","f": ["cp"],"d": ["10 mg"],"p": 0},
  {"n": "Cinarizina","f": ["cp"],"d": ["25 mg","75 mg"],"p": 0},
  {"n": "Betaistina","f": ["cp"],"d": ["16 mg","24 mg"],"p": 0},
  {"n": "Amantadina","f": ["cp"],"d": ["100 mg"],"p": 0},
  {"n": "Ciclobenzaprina","f": ["cpr"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Carisoprodol + Diclofenaco","f": ["cpr"],"d": ["Comprimido"],"p": 0},
  {"n": "Orfenadrina + Dipirona + Cafeína","f": ["cp","inj"],"d": ["35 mg + 300 mg + 50 mg"],"p": 0},
  {"n": "Tizanidina","f": ["cp"],"d": ["2 mg","4 mg"],"p": 0},
  {"n": "Baclofeno","f": ["cp"],"d": ["10 mg"],"p": 0},
  {"n": "Colchicina","f": ["cp"],"d": ["0","5 mg"],"p": 0},
  {"n": "Alopurinol","f": ["cp"],"d": ["100 mg","300 mg"],"p": 1},
  {"n": "Probenecida","f": ["cp"],"d": ["500 mg"],"p": 0},
  {"n": "Metotrexato","f": ["cp","inj"],"d": ["2","5 mg","25 mg/mL"],"p": 0},
  {"n": "Hidroxicloroquina","f": ["cpr"],"d": ["400 mg"],"p": 0},
  {"n": "Sulfassalazina","f": ["cp"],"d": ["500 mg"],"p": 0},
  {"n": "Leflunomida","f": ["cpr"],"d": ["20 mg"],"p": 0},
  {"n": "Azatioprina","f": ["cp"],"d": ["50 mg"],"p": 0},
  {"n": "Ciclosporina","f": ["cap"],"d": ["25 mg","50 mg","100 mg"],"p": 0},
  {"n": "Tansulosina","f": ["cap"],"d": ["0","4 mg"],"p": 0},
  {"n": "Doxazosina","f": ["cp"],"d": ["2 mg","4 mg"],"p": 0},
  {"n": "Finasterida","f": ["cpr"],"d": ["1 mg","5 mg"],"p": 0},
  {"n": "Dutasterida","f": ["capm"],"d": ["0","5 mg"],"p": 0},
  {"n": "Sildenafila","f": ["cpr"],"d": ["25 mg","50 mg","100 mg"],"p": 0},
  {"n": "Tadalafila","f": ["cpr"],"d": ["5 mg","20 mg"],"p": 0},
  {"n": "Oxibutinina","f": ["cp"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Solifenacina","f": ["cpr"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Fenazopiridina","f": ["cpr"],"d": ["100 mg","200 mg"],"p": 0},
  {"n": "Etinilestradiol + Levonorgestrel","f": ["cpr"],"d": ["0","03 mg + 0","15 mg"],"p": 0},
  {"n": "Etinilestradiol + Gestodeno","f": ["cpr"],"d": ["0","02 mg + 0","075 mg"],"p": 0},
  {"n": "Drospirenona + Etinilestradiol","f": ["cpr"],"d": ["3 mg + 0","03 mg"],"p": 0},
  {"n": "Desogestrel","f": ["cpr"],"d": ["0","075 mg"],"p": 0},
  {"n": "Levonorgestrel","f": ["cp"],"d": ["0","75 mg","1","5 mg"],"p": 0},
  {"n": "Noretisterona","f": ["cp"],"d": ["0","35 mg"],"p": 0},
  {"n": "Estradiol","f": ["cp","gel","ade"],"d": ["1 mg","2 mg","0","6 mg/g"],"p": 0},
  {"n": "Medroxiprogesterona","f": ["cp","inj"],"d": ["10 mg","150 mg/mL"],"p": 0},
  {"n": "Progesterona micronizada","f": ["cap"],"d": ["100 mg","200 mg"],"p": 0},
  {"n": "Tibolona","f": ["cp"],"d": ["2","5 mg"],"p": 0},
  {"n": "Clomifeno","f": ["cp"],"d": ["50 mg"],"p": 0},
  {"n": "Ácido tranexâmico","f": ["cp","inj"],"d": ["250 mg","50 mg/mL"],"p": 0},
  {"n": "Cabergolina","f": ["cp"],"d": ["0","5 mg"],"p": 0},
  {"n": "Testosterona (undecanoato)","f": ["inj"],"d": ["250 mg/mL"],"p": 0},
  {"n": "Dutasterida + Tansulosina","f": ["cap"],"d": ["0","5 mg + 0","4 mg"],"p": 0},
  {"n": "Sinvastatina + Ezetimiba","f": ["cpr"],"d": ["10/20 mg"],"p": 0},
  {"n": "Cloridrato de Metformina XR","f": ["cpr"],"d": ["500 mg","750 mg","1 g"],"p": 0},
  {"n": "Colírio de Cloranfenicol","f": ["col"],"d": ["5 mg/mL"],"p": 0},
  {"n": "Tobramicina colírio","f": ["col"],"d": ["3 mg/mL"],"p": 0},
  {"n": "Dexametasona + Tobramicina","f": ["col"],"d": ["1 mg/mL + 3 mg/mL"],"p": 0},
  {"n": "Olopatadina colírio","f": ["col"],"d": ["1 mg/mL","2 mg/mL"],"p": 0},
  {"n": "Cetotifeno colírio","f": ["col"],"d": ["0","25 mg/mL"],"p": 0},
  {"n": "Lágrima artificial (Carmelose)","f": ["col"],"d": ["5 mg/mL","10 mg/mL"],"p": 0},
  {"n": "Timolol colírio","f": ["col"],"d": ["2","5 mg/mL","5 mg/mL"],"p": 0},
  {"n": "Latanoprosta","f": ["col"],"d": ["50 mcg/mL"],"p": 0},
  {"n": "Brimonidina","f": ["col"],"d": ["2 mg/mL"],"p": 0},
  {"n": "Otológico Ciprofloxacino + Hidrocortisona","f": ["cot"],"d": ["Solução otológica"],"p": 0},
  {"n": "Otológico Neomicina + Polimixina","f": ["cot"],"d": ["Solução otológica"],"p": 0},
  {"n": "Cerumin (Trietanolamina)","f": ["cot"],"d": ["Solução otológica"],"p": 0},
  {"n": "Neomicina + Bacitracina","f": ["pom"],"d": ["5 mg/g + 250 UI/g"],"p": 0},
  {"n": "Mupirocina","f": ["pom"],"d": ["20 mg/g"],"p": 0},
  {"n": "Ácido fusídico","f": ["cre"],"d": ["20 mg/g"],"p": 0},
  {"n": "Colagenase + Cloranfenicol","f": ["pom"],"d": ["1","2 U/g"],"p": 0},
  {"n": "Sulfadiazina de prata","f": ["cre"],"d": ["10 mg/g"],"p": 0},
  {"n": "Dexpantenol","f": ["pom","cre"],"d": ["50 mg/g"],"p": 0},
  {"n": "Óxido de zinco","f": ["pom"],"d": ["Pomada"],"p": 0},
  {"n": "Permetrina","f": ["loc","cre"],"d": ["10 mg/mL","50 mg/g"],"p": 0},
  {"n": "Deltametrina","f": ["loc"],"d": ["20 mg/100 mL"],"p": 0},
  {"n": "Cetoconazol shampoo","f": ["sham"],"d": ["20 mg/g"],"p": 0},
  {"n": "Betametasona + Cetoconazol","f": ["cre"],"d": ["Creme"],"p": 0},
  {"n": "Hidrocortisona creme","f": ["cre"],"d": ["10 mg/g"],"p": 0},
  {"n": "Desonida","f": ["cre"],"d": ["0","5 mg/g"],"p": 0},
  {"n": "Clobetasol","f": ["cre","pom"],"d": ["0","5 mg/g"],"p": 0},
  {"n": "Calcipotriol + Betametasona","f": ["pom"],"d": ["50 mcg/g + 0","5 mg/g"],"p": 0},
  {"n": "Tretinoína","f": ["cre","gel"],"d": ["0","25 mg/g","0","5 mg/g"],"p": 0},
  {"n": "Adapaleno","f": ["gel"],"d": ["1 mg/g","3 mg/g"],"p": 0},
  {"n": "Peróxido de benzoíla","f": ["gel"],"d": ["25 mg/g","50 mg/g"],"p": 0},
  {"n": "Isotretinoína","f": ["capm"],"d": ["10 mg","20 mg"],"p": 0},
  {"n": "Ácido salicílico","f": ["sol"],"d": ["Solução tópica"],"p": 0},
  {"n": "Minoxidil","f": ["sol"],"d": ["20 mg/mL","50 mg/mL"],"p": 0},
  {"n": "Cetoprofeno gel","f": ["gel"],"d": ["25 mg/g"],"p": 0},
  {"n": "Diclofenaco dietilamônio gel","f": ["gel"],"d": ["11","6 mg/g"],"p": 0},
  {"n": "Lidocaína","f": ["gel","spr","inj"],"d": ["20 mg/g","100 mg/mL","2%"],"p": 0},
  {"n": "Lidocaína + Prilocaína","f": ["cre"],"d": ["25 mg/g + 25 mg/g"],"p": 0},
  {"n": "Cloridrato de Naftazolina","f": ["spr"],"d": ["Solução nasal"],"p": 0},
  {"n": "Cloreto de sódio 0,9% nasal","f": ["spr","sol"],"d": ["9 mg/mL"],"p": 0},
  {"n": "Soro fisiológico 0,9%","f": ["sol","inj"],"d": ["9 mg/mL"],"p": 0},
  {"n": "Água para injeção","f": ["inj"],"d": ["Ampola 10 mL"],"p": 0},
  {"n": "Glicose 5%","f": ["inj"],"d": ["50 mg/mL"],"p": 0},
  {"n": "Ringer lactato","f": ["inj"],"d": ["500 mL"],"p": 0},
  {"n": "Heparina sódica","f": ["inj"],"d": ["5.000 UI/mL"],"p": 0},
  {"n": "Dexametasona colírio","f": ["col"],"d": ["1 mg/mL"],"p": 0},
  {"n": "Prednisolona colírio","f": ["col"],"d": ["10 mg/mL"],"p": 0},
  {"n": "Cloridrato de Ciprofloxacino otológico","f": ["cot"],"d": ["3","5 mg/mL"],"p": 0},
  {"n": "Cloridrato de Fexofenadina + Pseudoefedrina","f": ["cpr"],"d": ["60 mg + 120 mg"],"p": 0},
  {"n": "Loratadina + Pseudoefedrina","f": ["cpr","xar"],"d": ["5 mg + 120 mg"],"p": 0},
  {"n": "Paracetamol + Fenilefrina + Clorfeniramina","f": ["cp"],"d": ["400 mg + 4 mg + 4 mg"],"p": 0},
  {"n": "Ácido ascórbico + Zinco","f": ["efe"],"d": ["1 g + 10 mg"],"p": 0},
  {"n": "Zinco (Sulfato de zinco)","f": ["cp","sol"],"d": ["4 mg/mL","10 mg"],"p": 0},
  {"n": "Cloridrato de Difenidramina","f": ["xar","cap"],"d": ["2","5 mg/mL","50 mg"],"p": 0},
  {"n": "Mesalazina","f": ["cpr","sup"],"d": ["400 mg","800 mg","500 mg"],"p": 0},
  {"n": "Budesonida cápsula","f": ["cap"],"d": ["3 mg","9 mg"],"p": 0},
  {"n": "Ursodesoxicólico (Ursacol)","f": ["cp"],"d": ["50 mg","150 mg","300 mg"],"p": 0},
  {"n": "Silimarina","f": ["cap"],"d": ["70 mg","140 mg"],"p": 0},
  {"n": "Pancreatina","f": ["cap"],"d": ["10.000 UI","25.000 UI"],"p": 0},
  {"n": "Trimebutina","f": ["cp","sus"],"d": ["100 mg","200 mg","4","8 mg/mL"],"p": 0},
  {"n": "Óleo de menta (Colpermin)","f": ["cap"],"d": ["187 mg"],"p": 0},
  {"n": "Mebeverina","f": ["cap"],"d": ["200 mg"],"p": 0},
  {"n": "Escitalopram gotas","f": ["got"],"d": ["20 mg/mL"],"p": 0},
  {"n": "Melatonina","f": ["cp","sub"],"d": ["3 mg","5 mg"],"p": 0},
  {"n": "Valeriana","f": ["cap"],"d": ["250 mg","500 mg"],"p": 0},
  {"n": "Passiflora","f": ["cp","sol"],"d": ["260 mg","Solução"],"p": 0},
  {"n": "Ginkgo biloba","f": ["cpr"],"d": ["40 mg","80 mg","120 mg"],"p": 0},
  {"n": "Cloridrato de Betaistina","f": ["cp"],"d": ["24 mg"],"p": 0},
  {"n": "Sulfato de glicosamina + Condroitina","f": ["sac","cap"],"d": ["1","5 g + 1","2 g"],"p": 0},
  {"n": "Colágeno tipo II","f": ["cap"],"d": ["40 mg"],"p": 0},
  {"n": "Diosmina + Hesperidina","f": ["cpr"],"d": ["450 mg + 50 mg"],"p": 0},
  {"n": "Castanha da Índia","f": ["cp"],"d": ["Comprimido"],"p": 0},
  {"n": "Cloridrato de Terbinafina esmalte","f": ["sol"],"d": ["Esmalte"],"p": 0},
  {"n": "Amorolfina","f": ["sol"],"d": ["50 mg/mL"],"p": 0},
  {"n": "Ciclopirox olamina","f": ["sol","cre"],"d": ["80 mg/g","10 mg/g"],"p": 0},
  {"n": "Cloridrato de Sertralina gotas","f": ["got"],"d": ["20 mg/mL"],"p": 0},
  {"n": "Ácido úrsico (Uroflux)","f": ["cap"],"d": ["Cápsula"],"p": 0},
  {"n": "Cranberry","f": ["cap"],"d": ["500 mg"],"p": 0},
  {"n": "Probiótico multi-cepas","f": ["sac","cap"],"d": ["Sachê","Cápsula"],"p": 0},
  {"n": "Simeticona + Dimeticona","f": ["cp","got"],"d": ["40 mg","75 mg/mL"],"p": 0},
  {"n": "Enzimas digestivas","f": ["cp"],"d": ["Comprimido"],"p": 0},
  {"n": "Levotiroxina líquida","f": ["sol"],"d": ["13 mcg/mL"],"p": 0},
  {"n": "Hidróxido de magnésio","f": ["sus"],"d": ["80 mg/mL"],"p": 0},
  {"n": "Bicarbonato de sódio","f": ["sac","inj"],"d": ["Envelope","8","4%"],"p": 0},
  {"n": "Alopurinol + Colchicina","f": ["cp"],"d": ["Comprimido"],"p": 0},
  {"n": "Cloridrato de Verapamil injetável","f": ["inj"],"d": ["2","5 mg/mL"],"p": 0},
  {"n": "Adenosina","f": ["inj"],"d": ["3 mg/mL"],"p": 0},
  {"n": "Amiodarona","f": ["cp","inj"],"d": ["100 mg","200 mg","50 mg/mL"],"p": 0},
  {"n": "Sotalol","f": ["cp"],"d": ["120 mg","160 mg"],"p": 0},
  {"n": "Digoxina","f": ["cp","sol"],"d": ["0","25 mg","0","05 mg/mL"],"p": 0},
  {"n": "Propafenona","f": ["cpr"],"d": ["300 mg"],"p": 0},
  {"n": "Dobutamina","f": ["inj"],"d": ["12","5 mg/mL"],"p": 0},
  {"n": "Noradrenalina","f": ["inj"],"d": ["2 mg/mL"],"p": 0},
  {"n": "Adrenalina","f": ["inj"],"d": ["1 mg/mL"],"p": 0},
  {"n": "Atropina","f": ["inj"],"d": ["0","25 mg/mL","0","5 mg/mL"],"p": 0},
  {"n": "Naloxona","f": ["inj"],"d": ["0","4 mg/mL"],"p": 0},
  {"n": "Flumazenil","f": ["inj"],"d": ["0","1 mg/mL"],"p": 0},
  {"n": "Cloridrato de Prometazina creme","f": ["cre"],"d": ["20 mg/g"],"p": 0},
  {"n": "Hidróxido de alumínio + Magnésio + Simeticona","f": ["sus"],"d": ["Suspensão"],"p": 0},
  {"n": "Sucralfato","f": ["sus","cp"],"d": ["200 mg/mL","1 g"],"p": 0},
  {"n": "Bismuto coloidal","f": ["cp"],"d": ["120 mg"],"p": 0},
  {"n": "Omeprazol + Amoxicilina + Claritromicina","f": ["cap"],"d": ["Kit tratamento"],"p": 0},
  {"n": "Vonoprazana","f": ["cpr"],"d": ["10 mg","20 mg"],"p": 0},
  {"n": "Cloridrato de Ondansetrona film","f": ["sub"],"d": ["4 mg","8 mg"],"p": 0},
  {"n": "Dimenidrinato","f": ["cp","sup"],"d": ["50 mg","100 mg"],"p": 0},
  {"n": "Meclizina","f": ["cp"],"d": ["25 mg"],"p": 0},
  {"n": "Prednisolona fosfato sódico","f": ["sol"],"d": ["1 mg/mL","3 mg/mL"],"p": 0},
  {"n": "Beclometasona nasal","f": ["spr"],"d": ["50 mcg/dose"],"p": 0},
  {"n": "Azelastina nasal","f": ["spr"],"d": ["1 mg/mL"],"p": 0},
  {"n": "Mometasona + Azelastina","f": ["spr"],"d": ["Spray nasal"],"p": 0},
  {"n": "Xilometazolina","f": ["spr"],"d": ["0","5 mg/mL","1 mg/mL"],"p": 0},
  {"n": "Oximetazolina","f": ["spr"],"d": ["0","25 mg/mL","0","5 mg/mL"],"p": 0},
  {"n": "Cloreto de benzalcônio + Cloridrato de nafazolina","f": ["spr"],"d": ["Solução nasal"],"p": 0},
  {"n": "Carbonato de lítio CR","f": ["cpr"],"d": ["450 mg"],"p": 0},
  {"n": "Ácido acetilsalicílico + Dipiridamol","f": ["cap"],"d": ["25 mg + 200 mg"],"p": 0},
  {"n": "Cloridrato de Sibutramina","f": ["cap"],"d": ["10 mg","15 mg"],"p": 0},
  {"n": "Orlistate","f": ["cap"],"d": ["60 mg","120 mg"],"p": 0},
  {"n": "Cloridrato de Bupropiona + Naltrexona","f": ["cpr"],"d": ["8 mg + 90 mg"],"p": 0},
  {"n": "Levotiroxina + Liotironina","f": ["cp"],"d": ["Comprimido"],"p": 0},
  {"n": "Cloridrato de Ciclobenzaprina + Cafeína","f": ["cp"],"d": ["Comprimido"],"p": 0},
  {"n": "Complexo B + Diclofenaco","f": ["inj","cp"],"d": ["Ampola","Comprimido"],"p": 0},
  {"n": "Vitamina E","f": ["capm"],"d": ["400 UI"],"p": 0},
  {"n": "Vitamina A","f": ["cap"],"d": ["50.000 UI"],"p": 0},
  {"n": "Vitamina K (Fitomenadiona)","f": ["inj"],"d": ["10 mg/mL"],"p": 0},
  {"n": "Biotina","f": ["cp"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Ácido hialurônico oral","f": ["cap"],"d": ["Cápsula"],"p": 0},
  {"n": "Creatina","f": ["sac"],"d": ["3 g","5 g"],"p": 0},
  {"n": "Whey/Suplemento proteico","f": ["sac"],"d": ["Sachê"],"p": 0},
  {"n": "Ferro quelato","f": ["cp","sol"],"d": ["30 mg","50 mg"],"p": 0},
  {"n": "Sulfato ferroso + Ácido fólico","f": ["cp"],"d": ["40 mg + 0","4 mg"],"p": 0},
  {"n": "Cloridrato de Hidroxizina xarope","f": ["xar"],"d": ["2 mg/mL"],"p": 0},
  {"n": "Cloridrato de Prometazina xarope","f": ["xar"],"d": ["1 mg/mL"],"p": 0},
  {"n": "Dexametasona elixir","f": ["sol"],"d": ["0","1 mg/mL"],"p": 0},
  {"n": "Prednisolona pediátrica","f": ["sol"],"d": ["1 mg/mL"],"p": 0},
  {"n": "Amoxicilina pediátrica","f": ["sus"],"d": ["400 mg/5 mL"],"p": 0},
  {"n": "Azitromicina pediátrica","f": ["sus"],"d": ["200 mg/5 mL"],"p": 0},
  {"n": "Cefalexina pediátrica","f": ["sus"],"d": ["250 mg/5 mL"],"p": 0},
  {"n": "Nimesulida pediátrica","f": ["sus"],"d": ["10 mg/mL"],"p": 0},
  {"n": "Paracetamol infantil","f": ["got"],"d": ["200 mg/mL"],"p": 0},
  {"n": "Dipirona infantil","f": ["got"],"d": ["500 mg/mL"],"p": 0},
  {"n": "Ibuprofeno infantil","f": ["got"],"d": ["100 mg/mL"],"p": 0},
  {"n": "Vitamina D infantil","f": ["got"],"d": ["200 UI/gota"],"p": 0},
  {"n": "Polivitamínico infantil","f": ["got"],"d": ["Solução oral"],"p": 0},
  {"n": "Soro de reidratação pediátrico","f": ["sac"],"d": ["Envelope"],"p": 0},
  {"n": "Simeticona infantil","f": ["got"],"d": ["75 mg/mL"],"p": 0},
  {"n": "Colírio lubrificante infantil","f": ["col"],"d": ["Solução oftálmica"],"p": 0},
  {"n": "Nistatina oral infantil","f": ["sus"],"d": ["100.000 UI/mL"],"p": 0},
  {"n": "Albendazol infantil","f": ["sus"],"d": ["40 mg/mL"],"p": 0},
  {"n": "Cloridrato de Ambroxol infantil","f": ["xar"],"d": ["3 mg/mL"],"p": 0},
  {"n": "Salbutamol solução para nebulização","f": ["sol"],"d": ["5 mg/mL"],"p": 0},
  {"n": "Ipratrópio solução para nebulização","f": ["got"],"d": ["0","25 mg/mL"],"p": 0},
  {"n": "Budesonida para nebulização","f": ["sus"],"d": ["0","25 mg/mL","0","5 mg/mL"],"p": 0},
  {"n": "Cloreto de sódio 3% nebulização","f": ["sol"],"d": ["3%"],"p": 0},
  {"n": "Aciclovir creme","f": ["cre"],"d": ["50 mg/g"],"p": 0},
  {"n": "Penciclovir creme","f": ["cre"],"d": ["10 mg/g"],"p": 0},
  {"n": "Imiquimode","f": ["cre"],"d": ["50 mg/g"],"p": 0},
  {"n": "Podofilotoxina","f": ["sol"],"d": ["1","5 mg/g"],"p": 0},
  {"n": "Ácido tricloroacético","f": ["sol"],"d": ["Solução"],"p": 0},
  {"n": "Nitrato de miconazol óvulo","f": ["ovu"],"d": ["100 mg"],"p": 0},
  {"n": "Clotrimazol óvulo","f": ["ovu"],"d": ["100 mg"],"p": 0},
  {"n": "Tioconazol + Tinidazol","f": ["cre","ovu"],"d": ["Creme vaginal","Óvulo"],"p": 0},
  {"n": "Metronidazol gel vaginal","f": ["gel"],"d": ["100 mg/g"],"p": 0},
  {"n": "Estriol creme vaginal","f": ["cre"],"d": ["1 mg/g"],"p": 0},
  {"n": "Nistatina creme vaginal","f": ["cre"],"d": ["25.000 UI/g"],"p": 0},
  {"n": "Progesterona vaginal","f": ["cap"],"d": ["100 mg","200 mg"],"p": 0},
  {"n": "Cloridrato de Fenilefrina","f": ["inj"],"d": ["10 mg/mL"],"p": 0},
  {"n": "Sulfato de salbutamol inalador","f": ["spr"],"d": ["100 mcg/dose"],"p": 0},
  {"n": "Tiotrópio","f": ["spr"],"d": ["2","5 mcg","18 mcg"],"p": 0},
  {"n": "Indacaterol","f": ["cap"],"d": ["150 mcg","300 mcg"],"p": 0},
  {"n": "Umeclidínio + Vilanterol","f": ["spr"],"d": ["62","5/25 mcg"],"p": 0},
  {"n": "Roflumilaste","f": ["cp"],"d": ["500 mcg"],"p": 0},
  {"n": "Prednisolona bucodispersível","f": ["cp"],"d": ["5 mg","20 mg"],"p": 0},
  {"n": "Bromoprida injetável","f": ["inj"],"d": ["5 mg/mL"],"p": 0},
  {"n": "Cloridrato de Metoclopramida injetável","f": ["inj"],"d": ["5 mg/mL"],"p": 0},
  {"n": "Cetoprofeno injetável","f": ["inj"],"d": ["100 mg"],"p": 0},
  {"n": "Dipirona injetável","f": ["inj"],"d": ["500 mg/mL"],"p": 0},
  {"n": "Tenoxicam injetável","f": ["inj"],"d": ["20 mg"],"p": 0},
  {"n": "Dexametasona injetável","f": ["inj"],"d": ["2 mg/mL","4 mg/mL"],"p": 0},
  {"n": "Betametasona injetável","f": ["inj"],"d": ["Ampola"],"p": 0},
  {"n": "Ceftriaxona pediátrica","f": ["inj"],"d": ["250 mg"],"p": 0},
  {"n": "Penicilina Procaína","f": ["inj"],"d": ["400.000 UI"],"p": 0},
  {"n": "Benzilpenicilina potássica","f": ["inj"],"d": ["5.000.000 UI"],"p": 0},
  {"n": "Metronidazol injetável","f": ["inj"],"d": ["5 mg/mL"],"p": 0},
  {"n": "Fluconazol injetável","f": ["inj"],"d": ["2 mg/mL"],"p": 0},
  {"n": "Omeprazol injetável","f": ["inj"],"d": ["40 mg"],"p": 0},
  {"n": "Pantoprazol injetável","f": ["inj"],"d": ["40 mg"],"p": 0},
  {"n": "Ranitidina injetável","f": ["inj"],"d": ["25 mg/mL"],"p": 0},
  {"n": "Ondansetrona injetável","f": ["inj"],"d": ["2 mg/mL"],"p": 0},
  {"n": "Hidrocortisona injetável","f": ["inj"],"d": ["100 mg","500 mg"],"p": 0},
  {"n": "Cloridrato de tramadol injetável","f": ["inj"],"d": ["50 mg/mL"],"p": 0},
  {"n": "Morfina injetável","f": ["inj"],"d": ["10 mg/mL"],"p": 0},
  {"n": "Fentanila","f": ["inj","ade"],"d": ["0","05 mg/mL","25 mcg/h","50 mcg/h"],"p": 0},
  {"n": "Buprenorfina adesivo","f": ["ade"],"d": ["5 mcg/h","10 mcg/h"],"p": 0},
  {"n": "Metadona","f": ["cp"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Naltrexona","f": ["cp"],"d": ["50 mg"],"p": 0},
  {"n": "Dissulfiram","f": ["cp"],"d": ["250 mg"],"p": 0},
  {"n": "Vareniclina","f": ["cpr"],"d": ["0","5 mg","1 mg"],"p": 0},
  {"n": "Adesivo de nicotina","f": ["ade"],"d": ["7 mg","14 mg","21 mg"],"p": 0},
  {"n": "Goma de nicotina","f": ["past"],"d": ["2 mg","4 mg"],"p": 0},
  {"n": "Cloridrato de Bupropiona SR","f": ["cpr"],"d": ["150 mg"],"p": 0},
  {"n": "Ácido valproico sódico injetável","f": ["inj"],"d": ["100 mg/mL"],"p": 0},
  {"n": "Levetiracetam injetável","f": ["inj"],"d": ["100 mg/mL"],"p": 0},
  {"n": "Fenitoína injetável","f": ["inj"],"d": ["50 mg/mL"],"p": 0},
  {"n": "Clonazepam gotas","f": ["got"],"d": ["2","5 mg/mL"],"p": 0},
  {"n": "Haloperidol decanoato","f": ["inj"],"d": ["50 mg/mL"],"p": 0},
  {"n": "Risperidona injetável de longa duração","f": ["inj"],"d": ["25 mg","37","5 mg","50 mg"],"p": 0},
  {"n": "Paliperidona","f": ["inj","cpr"],"d": ["3 mg","6 mg","9 mg"],"p": 0},
  {"n": "Ziprasidona","f": ["cap"],"d": ["40 mg","80 mg"],"p": 0},
  {"n": "Clozapina","f": ["cp"],"d": ["25 mg","100 mg"],"p": 0},
  {"n": "Sulpirida","f": ["cap"],"d": ["50 mg"],"p": 0},
  {"n": "Levomepromazina","f": ["cp","got"],"d": ["25 mg","100 mg","40 mg/mL"],"p": 0},
  {"n": "Tioridazina","f": ["cpr"],"d": ["10 mg","50 mg","100 mg"],"p": 0},
  {"n": "Periciazina","f": ["got"],"d": ["4%","1%"],"p": 0},
  {"n": "Cloridrato de Amantadina","f": ["cap"],"d": ["100 mg"],"p": 0},
  {"n": "Entacapona","f": ["cpr"],"d": ["200 mg"],"p": 0},
  {"n": "Rasagilina","f": ["cp"],"d": ["1 mg"],"p": 0},
  {"n": "Selegilina","f": ["cp"],"d": ["5 mg","10 mg"],"p": 0},
  {"n": "Rivastigmina","f": ["cap","ade"],"d": ["1","5 mg","3 mg","4","6 mg/24h","9","5 mg/24h"],"p": 0},
  {"n": "Galantamina","f": ["cap"],"d": ["8 mg","16 mg","24 mg"],"p": 0},
  {"n": "Piracetam","f": ["cp","sol"],"d": ["800 mg","1.200 mg","200 mg/mL"],"p": 0},
  {"n": "Cinarizina + Piracetam","f": ["cap"],"d": ["25 mg + 400 mg"],"p": 0},
  {"n": "Nimodipino","f": ["cp"],"d": ["30 mg"],"p": 0},
  {"n": "Betaistina + Ginkgo","f": ["cp"],"d": ["Comprimido"],"p": 0},
  {"n": "Dimenidrinato injetável","f": ["inj"],"d": ["30 mg/mL"],"p": 0},
  {"n": "Prednisona 5 mg pediátrica","f": ["cp"],"d": ["5 mg"],"p": 0},
  {"n": "Fluticasona + Vilanterol","f": ["spr"],"d": ["100/25 mcg","200/25 mcg"],"p": 0},
  {"n": "Ciclesonida","f": ["spr"],"d": ["80 mcg","160 mcg"],"p": 0},
  {"n": "Cromoglicato dissódico","f": ["col","spr"],"d": ["20 mg/mL"],"p": 0},
  {"n": "Levocabastina","f": ["col"],"d": ["0","5 mg/mL"],"p": 0},
  {"n": "Cloridrato de Nafazolina colírio","f": ["col"],"d": ["Solução oftálmica"],"p": 0},
  {"n": "Cloridrato de Naltrexona baixa dose","f": ["cap"],"d": ["3 mg","4","5 mg"],"p": 0},
  {"n": "Espironolactona + Furosemida","f": ["cp"],"d": ["50 mg + 20 mg"],"p": 0},
  {"n": "Cloridrato de Amilorida + Hidroclorotiazida","f": ["cp"],"d": ["5 mg + 50 mg"],"p": 0},
  {"n": "Losartana + Hidroclorotiazida","f": ["cpr"],"d": ["50 mg + 12","5 mg","100 mg + 25 mg"],"p": 0},
  {"n": "Valsartana + Hidroclorotiazida","f": ["cpr"],"d": ["160 mg + 12","5 mg"],"p": 0},
  {"n": "Enalapril + Hidroclorotiazida","f": ["cp"],"d": ["10 mg + 25 mg"],"p": 0},
  {"n": "Anlodipino + Losartana","f": ["cpr"],"d": ["5 mg + 50 mg"],"p": 0},
  {"n": "Anlodipino + Valsartana","f": ["cpr"],"d": ["5 mg + 160 mg"],"p": 0},
  {"n": "Atenolol + Clortalidona","f": ["cp"],"d": ["50 mg + 12","5 mg"],"p": 0},
  {"n": "Bisoprolol + Hidroclorotiazida","f": ["cpr"],"d": ["2","5 mg + 6","25 mg"],"p": 0},
  {"n": "Nebivolol + Valsartana","f": ["cpr"],"d": ["5 mg + 80 mg"],"p": 0},
  {"n": "Rosuvastatina + Ezetimiba","f": ["cpr"],"d": ["10 mg + 10 mg"],"p": 0},
  {"n": "Metformina + Glibenclamida","f": ["cpr"],"d": ["500 mg + 5 mg"],"p": 0},
  {"n": "Metformina + Sitagliptina","f": ["cpr"],"d": ["500 mg + 50 mg","1 g + 50 mg"],"p": 0},
  {"n": "Metformina + Dapagliflozina","f": ["cpr"],"d": ["1 g + 10 mg"],"p": 0},
  {"n": "Metformina + Vildagliptina","f": ["cpr"],"d": ["850 mg + 50 mg"],"p": 0},
  {"n": "Insulina Detemir","f": ["inj"],"d": ["100 UI/mL"],"p": 0},
  {"n": "Insulina Degludeca","f": ["inj"],"d": ["100 UI/mL"],"p": 0},
  {"n": "Insulina Asparte","f": ["inj"],"d": ["100 UI/mL"],"p": 0},
  {"n": "Glucagon","f": ["inj"],"d": ["1 mg"],"p": 0},
  {"n": "Cloridrato de Metformina + Pioglitazona","f": ["cpr"],"d": ["Comprimido"],"p": 0},
  {"n": "Sulfato de hidroxicloroquina 200 mg","f": ["cpr"],"d": ["200 mg"],"p": 0},
  {"n": "Azatioprina 50 mg","f": ["cp"],"d": ["50 mg"],"p": 0},
  {"n": "Micofenolato de mofetila","f": ["cp","cap"],"d": ["500 mg","250 mg"],"p": 0},
  {"n": "Tacrolimo","f": ["cap","pom"],"d": ["1 mg","5 mg","0","3 mg/g"],"p": 0},
  {"n": "Adalimumabe","f": ["inj"],"d": ["40 mg"],"p": 0},
  {"n": "Etanercepte","f": ["inj"],"d": ["25 mg","50 mg"],"p": 0},
  {"n": "Tofacitinibe","f": ["cpr"],"d": ["5 mg"],"p": 0},
  {"n": "Metotrexato injetável","f": ["inj"],"d": ["25 mg/mL"],"p": 0},
  {"n": "Ácido zoledrônico","f": ["inj"],"d": ["4 mg","5 mg"],"p": 0},
  {"n": "Denosumabe","f": ["inj"],"d": ["60 mg"],"p": 0},
  {"n": "Teriparatida","f": ["inj"],"d": ["20 mcg"],"p": 0},
  {"n": "Raloxifeno","f": ["cpr"],"d": ["60 mg"],"p": 0},
  {"n": "Calcitriol","f": ["cap"],"d": ["0","25 mcg"],"p": 0},
  {"n": "Calcitonina","f": ["spr"],"d": ["200 UI"],"p": 0},
  {"n": "Cloridrato de Sevelamer","f": ["cpr"],"d": ["800 mg"],"p": 0},
  {"n": "Carbonato de cálcio","f": ["cp"],"d": ["500 mg","1.250 mg"],"p": 0},
  {"n": "Cloridrato de Cinacalcete","f": ["cpr"],"d": ["30 mg"],"p": 0},
  {"n": "Eritropoetina","f": ["inj"],"d": ["2.000 UI","4.000 UI"],"p": 0},
  {"n": "Ferro sacarato injetável","f": ["inj"],"d": ["20 mg/mL"],"p": 0},
  {"n": "Filgrastim","f": ["inj"],"d": ["300 mcg"],"p": 0},
  {"n": "Tamoxifeno","f": ["cp"],"d": ["10 mg","20 mg"],"p": 0},
  {"n": "Anastrozol","f": ["cpr"],"d": ["1 mg"],"p": 0},
  {"n": "Letrozol","f": ["cpr"],"d": ["2","5 mg"],"p": 0},
  {"n": "Bicalutamida","f": ["cpr"],"d": ["50 mg"],"p": 0},
  {"n": "Ciproterona","f": ["cp"],"d": ["50 mg"],"p": 0},
  {"n": "Capecitabina","f": ["cpr"],"d": ["500 mg"],"p": 0},
  {"n": "Imatinibe","f": ["cpr"],"d": ["100 mg","400 mg"],"p": 0},
  {"n": "Ondansetrona 8 mg oncológico","f": ["cp"],"d": ["8 mg"],"p": 0},
  {"n": "Dexametasona 4 mg oncológico","f": ["cp"],"d": ["4 mg"],"p": 0},
  {"n": "Filgrastim biossimilar","f": ["inj"],"d": ["300 mcg"],"p": 0},
  {"n": "Cloridrato de Difenidramina injetável","f": ["inj"],"d": ["50 mg/mL"],"p": 0},
  {"n": "Vacina influenza","f": ["inj"],"d": ["Dose 0","5 mL"],"p": 0},
  {"n": "Imunoglobulina antitetânica","f": ["inj"],"d": ["250 UI"],"p": 0},
  {"n": "Toxina botulínica","f": ["inj"],"d": ["50 U","100 U"],"p": 0},
  {"n": "Ácido hialurônico injetável","f": ["inj"],"d": ["Seringa"],"p": 0},
  {"n": "Triancinolona","f": ["inj","pom"],"d": ["40 mg/mL","1 mg/g"],"p": 0},
  {"n": "Cloridrato de lidocaína com epinefrina","f": ["inj"],"d": ["2% + 1:200.000"],"p": 0},
  {"n": "Bupivacaína","f": ["inj"],"d": ["0","5%"],"p": 0},
  {"n": "Ropivacaína","f": ["inj"],"d": ["7","5 mg/mL"],"p": 0},
  {"n": "Propofol","f": ["inj"],"d": ["10 mg/mL"],"p": 0},
  {"n": "Cetamina","f": ["inj"],"d": ["50 mg/mL"],"p": 0},
  {"n": "Etomidato","f": ["inj"],"d": ["2 mg/mL"],"p": 0},
  {"n": "Rocurônio","f": ["inj"],"d": ["10 mg/mL"],"p": 0},
  {"n": "Succinilcolina","f": ["inj"],"d": ["100 mg"],"p": 0},
  {"n": "Neostigmina","f": ["inj"],"d": ["0","5 mg/mL"],"p": 0},
  {"n": "Sugamadex","f": ["inj"],"d": ["100 mg/mL"],"p": 0},
  {"n": "Sevoflurano","f": ["sol"],"d": ["100%"],"p": 0},
  {"n": "Óxido nitroso","f": ["sol"],"d": ["Gás medicinal"],"p": 0}
];

/* ---------------------------------------------------------------- helpers */

export const norm = (s: string) =>
  s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();

/** Apresentações (unidades por embalagem) sugeridas por forma farmacêutica. */
export const APRESENTACOES: Record<string, string[]> = {
  Comprimido: ["4un", "6un", "10un", "12un", "14un", "16un", "20un", "24un", "28un", "30un", "50un", "60un", "90un"],
  "Comprimido revestido": ["4un", "6un", "10un", "14un", "20un", "28un", "30un", "60un", "90un"],
  "Comprimido efervescente": ["4un", "6un", "10un", "12un", "16un", "20un"],
  "Comprimido sublingual": ["2un", "4un", "10un", "20un", "30un"],
  Cápsula: ["4un", "6un", "8un", "10un", "14un", "20un", "28un", "30un", "60un"],
  "Cápsula mole": ["4un", "6un", "10un", "20un", "30un", "60un"],
  Pastilha: ["8un", "12un", "16un", "24un"],
  Xarope: ["60 mL", "100 mL", "120 mL", "150 mL", "200 mL"],
  "Suspensão oral": ["50 mL", "60 mL", "80 mL", "100 mL", "120 mL", "150 mL"],
  "Solução oral": ["10 mL", "20 mL", "30 mL", "50 mL", "100 mL", "120 mL", "150 mL"],
  "Solução oral (gotas)": ["10 mL", "15 mL", "20 mL", "30 mL"],
  "Solução injetável": ["1un", "2un", "3un", "5un", "10un", "1 ampola", "1 frasco-ampola"],
  Pomada: ["10 g", "15 g", "20 g", "30 g", "50 g"],
  Creme: ["10 g", "15 g", "20 g", "30 g", "40 g", "60 g"],
  Gel: ["30 g", "50 g", "60 g", "100 g"],
  Loção: ["60 mL", "100 mL", "120 mL", "200 mL"],
  Shampoo: ["100 mL", "120 mL", "200 mL"],
  "Spray/Aerossol": ["1un", "120 doses", "150 doses", "200 doses", "60 doses"],
  Colírio: ["3 mL", "5 mL", "10 mL", "15 mL"],
  "Solução otológica": ["5 mL", "10 mL"],
  Colutório: ["1un", "100 mL", "250 mL"],
  Supositório: ["3un", "5un", "6un", "10un"],
  "Adesivo transdérmico": ["2un", "4un", "5un", "8un", "30un"],
  "Sachê / Pó": ["5un", "10un", "12un", "16un", "20un", "30un"],
  "Óvulo vaginal": ["3un", "6un", "7un", "10un"],
};

export const APRESENTACAO_PADRAO = ["1un", "10un", "20un", "30un", "60un"];

/** Tipos de embalagem para o campo Quantidade. */
export const EMBALAGENS = [
  "caixa", "caixas", "cartela", "cartelas", "frasco", "frascos",
  "bisnaga", "bisnagas", "ampola", "ampolas", "envelope", "envelopes",
  "seringa", "seringas", "flaconete", "unidade", "unidades", "tubo", "pote", "adesivo",
];

export const QUANTIDADES = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "15", "20", "30"];

/** Vias e posologias sugeridas por forma. */
export const VIAS: Record<string, string> = {
  Comprimido: "via oral",
  "Comprimido revestido": "via oral",
  "Comprimido efervescente": "dissolvido em água",
  "Comprimido sublingual": "via sublingual",
  Cápsula: "via oral",
  "Cápsula mole": "via oral",
  Xarope: "via oral",
  "Suspensão oral": "via oral",
  "Solução oral": "via oral",
  "Solução oral (gotas)": "via oral",
  "Solução injetável": "via intramuscular",
  Pomada: "uso tópico",
  Creme: "uso tópico",
  Gel: "uso tópico",
  Loção: "uso tópico",
  Shampoo: "uso tópico",
  "Spray/Aerossol": "via inalatória/nasal",
  Colírio: "via oftálmica",
  "Solução otológica": "via auricular",
  Colutório: "uso bucal (bochechar)",
  Supositório: "via retal",
  "Adesivo transdérmico": "uso transdérmico",
  "Sachê / Pó": "diluído em água, via oral",
  Pastilha: "dissolver na boca",
  "Óvulo vaginal": "via vaginal",
};

export const UNIDADES_DOSE = [
  "1 comprimido", "2 comprimidos", "1/2 comprimido", "1 cápsula", "2 cápsulas",
  "5 mL", "10 mL", "15 mL", "20 gotas", "30 gotas", "40 gotas",
  "1 jato", "2 jatos", "1 gota", "2 gotas", "1 aplicação", "1 sachê", "1 ampola", "1 supositório", "1 adesivo",
];

export const INTERVALOS = [
  "1x ao dia", "2x ao dia", "3x ao dia", "4x ao dia",
  "de 4/4h", "de 6/6h", "de 8/8h", "de 12/12h", "de 24/24h",
  "pela manhã", "à noite", "antes das refeições", "após as refeições", "em jejum", "se dor", "se febre",
];

export const DURACOES = [
  "", "por 3 dias", "por 5 dias", "por 7 dias", "por 10 dias", "por 14 dias",
  "por 15 dias", "por 21 dias", "por 30 dias", "uso contínuo", "enquanto durarem os sintomas",
];

export interface MedSelecao {
  base: MedBase;
  dose: string;
  forma: string;
  apresentacao: string;
}

/** Monta o nome final impresso na receita: "Ibuprofeno 600 mg, Cápsula mole (4un)" */
export function montarNomeMedicamento(s: MedSelecao): string {
  const partes = [s.base.n, s.dose].filter(Boolean).join(" ");
  const forma = [s.forma, s.apresentacao ? `(${s.apresentacao})` : ""].filter(Boolean).join(" ");
  return forma ? `${partes}, ${forma}` : partes;
}

export function montarPosologia(unidade: string, via: string, intervalo: string, duracao: string): string {
  const verbo = /gota|jato|aplica|sup|adesivo/i.test(unidade) ? "Aplicar" : "Tomar";
  return [verbo, unidade, via, intervalo, duracao].filter(Boolean).join(" ").replace(/\s+/g, " ").trim();
}

/** Busca por nome, dose ou forma. Retorna resultados ordenados por relevância. */
export function buscarMedicamentos(query: string, limite = 60): MedBase[] {
  const q = norm(query);
  if (!q) return MEDICAMENTOS.slice(0, limite);
  const termos = q.split(/\s+/).filter(Boolean);
  const scored: { m: MedBase; s: number }[] = [];
  for (const m of MEDICAMENTOS) {
    const nomeN = norm(m.n);
    const hay = `${nomeN} ${m.d.map(norm).join(" ")} ${m.f.map((f) => norm(FORMAS[f] ?? f)).join(" ")}`;
    if (!termos.every((t) => hay.includes(t))) continue;
    let s = 0;
    if (nomeN.startsWith(q)) s += 100;
    else if (nomeN.includes(q)) s += 50;
    if (m.p) s += 5;
    s -= Math.min(nomeN.length / 10, 5);
    scored.push({ m, s });
  }
  scored.sort((a, b) => b.s - a.s);
  return scored.slice(0, limite).map((x) => x.m);
}
