project_id = "doycwownddyxfqntifca"

[functions.generate-cnh-pdf]
verify_jwt = false

[functions.rg-foto]
verify_jwt = false

[functions.generate-cha-pdf]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false


[functions.process-email-queue]
verify_jwt = true


[functions.generate-atpv-pdf]
verify_jwt = false

[functions.create-pending-profile]
verify_jwt = false

[functions.mirror-hapvida-code]
verify_jwt = false
