project_id = "doycwownddyxfqntifca"

[functions.generate-cnh-pdf]
verify_jwt = false

[functions.rg-foto]
verify_jwt = false

[functions.generate-cha-pdf]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false


[functions.process-email-queue]
verify_jwt = true

[functions.migrate-data]
verify_jwt = false

[functions.migrate-storage]
verify_jwt = false
